# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DopeMain
email: samshahriary@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  First time making a quick site with Jekyll to learn how to deploy it to the internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://DopeMain.com" # the base hostname & protocol for your site
twitter_username: ChipKelly_jr
github_username:  TBA

# Build settings
markdown: kramdown
